#!/bin/sh

set -e

# Test ucf update of user-modified file.

${UCF_TEST_BINDIR}ucf input.conf /tmp/input.conf 2>&1
echo "# Modified" >> /tmp/input.conf
${UCF_TEST_BINDIR}ucf input2.conf /tmp/input.conf 2>&1
