#!/bin/sh

set -e

# Test DPKG_FORCE=confask

touch /tmp/input.conf
${UCF_TEST_BINDIR}ucf /tmp/input.conf /tmp/input.conf 2>&1
DPKG_FORCE=confask ${UCF_TEST_BINDIR}ucf input.conf /tmp/input.conf 2>&1
