#!/bin/sh

set -e

# Test DPKG_FORCE=confdef overrides confnew

${UCF_TEST_BINDIR}ucf input.conf /tmp/input.conf 2>&1
echo "# Modified" >> /tmp/input.conf
DPKG_FORCE=confnew,confdef ${UCF_TEST_BINDIR}ucf input.conf /tmp/input.conf 2>&1
